baseurl = "https://blog.sero.ai"
languageCode = "en"
title = "Sero.ai"
theme = "Hucore"
copyright = "&copy; 2017 | <a href=\"https://github.com/mgjohansen/hucore.git\" target=\"_blank\">Hucore theme</a> & <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a> ♥"

[taxonomies]
tag = "tags"
category = "categories"

[params]
description = "Sero.ai Blog"
Keywords = ["sero.ai", "blog"]
author = "Tom Tran"
sharingicons = false
displayauthor = true

[params.highlight]
style = "github"
Languages = ["go", "dockerfile"]

[[params.social]]
url = "http://sero.ai"
fa_icon = "fa-home"

[[params.social]]
url = "https://github.com/seroai"
fa_icon = "fa-github"

[[params.social]]
url = "https://www.linkedin.com/company-beta/16208733/"
fa_icon = "fa-linkedin-square"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[params.socialshare]]
url = "https://www.linkedin.com/company-beta/16208733/"
fa_icon = "fa-linkedin-square"